/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CronTriggerRouteImport } from './routes/cron-trigger'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnitsUnitIdRouteImport } from './routes/units_.$unitId'

const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CronTriggerRoute = CronTriggerRouteImport.update({
  id: '/cron-trigger',
  path: '/cron-trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsUnitIdRoute = UnitsUnitIdRouteImport.update({
  id: '/units_/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/cron-trigger': typeof CronTriggerRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/instances': typeof InstancesRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/messages': typeof MessagesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/units': typeof UnitsRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/cron-trigger': typeof CronTriggerRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/instances': typeof InstancesRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/messages': typeof MessagesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/units': typeof UnitsRoute
  '/units/$unitId': typeof UnitsUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/cron-trigger': typeof CronTriggerRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/instances': typeof InstancesRoute
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRoute
  '/messages': typeof MessagesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/units': typeof UnitsRoute
  '/units_/$unitId': typeof UnitsUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/cron-trigger'
    | '/dashboard'
    | '/history'
    | '/instances'
    | '/login'
    | '/manager'
    | '/messages'
    | '/settings'
    | '/signup'
    | '/units'
    | '/units/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/cron-trigger'
    | '/dashboard'
    | '/history'
    | '/instances'
    | '/login'
    | '/manager'
    | '/messages'
    | '/settings'
    | '/signup'
    | '/units'
    | '/units/$unitId'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/cron-trigger'
    | '/dashboard'
    | '/history'
    | '/instances'
    | '/login'
    | '/manager'
    | '/messages'
    | '/settings'
    | '/signup'
    | '/units'
    | '/units_/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRoute
  CronTriggerRoute: typeof CronTriggerRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  InstancesRoute: typeof InstancesRoute
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRoute
  MessagesRoute: typeof MessagesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  UnitsRoute: typeof UnitsRoute
  UnitsUnitIdRoute: typeof UnitsUnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron-trigger': {
      id: '/cron-trigger'
      path: '/cron-trigger'
      fullPath: '/cron-trigger'
      preLoaderRoute: typeof CronTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units_/$unitId': {
      id: '/units_/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof UnitsUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRoute,
  CronTriggerRoute: CronTriggerRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  InstancesRoute: InstancesRoute,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRoute,
  MessagesRoute: MessagesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  UnitsRoute: UnitsRoute,
  UnitsUnitIdRoute: UnitsUnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
