// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseAdminClient() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    console.error("[Supabase Admin] ERRO: SUPABASE_URL ou SUPABASE_SERVICE_ROLE_KEY não encontrados.");
    return null;
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: any | null = null;

export const supabaseAdmin = {
  get client() {
    if (!_supabaseAdmin) {
      _supabaseAdmin = createSupabaseAdminClient();
    }
    if (!_supabaseAdmin) {
      throw new Error("Supabase Admin client is not initialized. Check your environment variables.");
    }
    return _supabaseAdmin;
  },
  // Proxy local para manter a sintaxe supabaseAdmin.from(...)
  from: (table: string) => supabaseAdmin.client.from(table),
  rpc: (name: string, args?: any) => supabaseAdmin.client.rpc(name, args),
  auth: {
    get admin() { return supabaseAdmin.client.auth.admin; }
  },
  storage: {
    from: (id: string) => supabaseAdmin.client.storage.from(id)
  }
};
